version: '3.8'

services:
  llm-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama:11434}
      - MODEL_NAME=${MODEL_NAME:-mistral}
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./models:/app/models
      - docker_cache:/var/lib/docker  # Cache Docker persistant
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
  docker_cache:  # Volume persistant pour le cache Docker 