# .github/workflows/docker-image.yml
name: Build & Push Docker image (cache)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1           # limite les appels simultanés
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase owner
        id: vars
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GHCR_PAT }}

      # Connexion Docker Hub (optionnelle)
      - name: Docker Hub login
        if: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Retry build on failure
        uses: Wandalen/wretry.action@v1
        with:
          action: docker/build-push-action@v5
          attempt_limit: 3
          attempt_delay: 30000      # en millisecondes
          with: |
            context: .
            push: true
            tags: ghcr.io/${{ env.OWNER_LC }}/tts_stt_misral:latest
            cache-from: type=gha
            cache-to: type=gha,mode=max
